name: CI-update-swagger
on:
  schedule:
  # 1-5: Monday to Friday (skip weekend)
  - cron: '0 12 * * 1-5'

env:
  GITHUB_TOKEN: ${{ secrets.CI_ROBOT_GITHUB_TOKEN }}

jobs:
  update:
    runs-on:
    - ubuntu-latest
    steps:
    # Checkout swagger-merger repository
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.CI_ROBOT_SSH_PRIVATE_KEY }}
    - name: checkout frontend
      run: |
        git clone git@github.com:llmariner/frontend.git
    - name: checkout dependencies
      run: |
        mkdir apis
        ./update_repos.sh apis
    - name: setup
      run: |
        npm install -g yarn
        rm -rf node_modules && yarn install
    - name: run
      run: |
        yarn regenerate apis frontend
